import { useState } from 'react';
import { DateInput } from '../../components/DateInput';
import { Money } from '../../components/Money';
import { useIpcQuery } from '../../hooks/useIpcQuery';
import { useUiStore } from '../../app/store/uiStore';
import type { CompliancePackageResult } from '@shared/domain/reporting/compliancePackage';
import { userAuditStyle } from '../../utils/userAuditColor';
import { localIsoDate } from '@shared/domain/dates/localDate';

export type ComplianceReportPageKind =
  | 'auditTrail' | 'sourceDocuments' | 'bankDepositAnalysis' | 'payrollRegister' | 'hstWorkingPaper'
  | 'fixedAssetContinuity' | 'shareholderContinuity' | 'inventoryContinuity' | 'debtContinuity' | 't2Reconciliation';

const COPY: Record<ComplianceReportPageKind, { title: string; note: string }> = {
  auditTrail: { title: 'Audit Trail / Change History', note: 'Journal creation and every retained before/after revision for the selected period.' },
  sourceDocuments: { title: 'Source Documents & Missing Evidence', note: 'Transactions tied to generated or attached evidence, with missing support called out.' },
  bankDepositAnalysis: { title: 'Bank Deposit Analysis', note: 'Every debit into a bank, cash, or transfer account, classified by its other side. Ambiguous items stay flagged.' },
  payrollRegister: { title: 'Payroll Register & Remittance Detail', note: 'Employee-by-employee gross pay, deductions, employer portions, net pay, and GL posting status.' },
  hstWorkingPaper: { title: 'GST/HST Return Working Paper', note: 'CRA return-line working figures tied to HST categories, manual exceptions, and the recorded filing.' },
  fixedAssetContinuity: { title: 'Fixed Asset / CCA Continuity', note: 'Opening UCC, additions, dispositions, CCA claimed, and closing UCC by class.' },
  shareholderContinuity: { title: 'Shareholder & Related-Party Continuity', note: 'Linked loan balances, dividends, interest, and missing identity information by shareholder.' },
  inventoryContinuity: { title: 'Inventory Movement & Valuation Continuity', note: 'Opening quantity plus receipts less issues to closing quantity and weighted-average value.' },
  debtContinuity: { title: 'Debt Continuity', note: 'Loan terms and original principal compared with the linked liability-account balance.' },
  t2Reconciliation: { title: 'T2 Preliminary Tax Reconciliation', note: 'Accounting income bridged to a preliminary tax-review figure and checked for missing GIFI mappings.' },
};

function todayIso() { return localIsoDate() }
function yearStartIso() { return `${todayIso().slice(0, 4)}-01-01` }
const Th = ({ children, right = false }: { children: React.ReactNode; right?: boolean }) => <th className={`px-3 py-2 text-xs font-medium uppercase tracking-wide text-gray-500 ${right ? 'text-right' : 'text-left'}`}>{children}</th>;
const Empty = ({ children = 'No rows for this period.' }: { children?: React.ReactNode }) => <p className="rounded border border-dashed border-gray-300 px-4 py-5 text-center text-sm text-gray-500">{children}</p>;
const Badge = ({ children, bad = false }: { children: React.ReactNode; bad?: boolean }) => <span className={`rounded px-2 py-0.5 text-xs font-medium ${bad ? 'bg-rose-50 text-rose-700' : 'bg-emerald-50 text-emerald-700'}`}>{children}</span>;

export function ComplianceReportPage({ report }: { report: ComplianceReportPageKind }) {
  const [periodStart, setPeriodStart] = useState(yearStartIso());
  const [periodEnd, setPeriodEnd] = useState(todayIso());
  const setView = useUiStore((state) => state.setView);
  const { data, loading, error } = useIpcQuery(() => window.api.reports.compliancePackage({ periodStart, periodEnd }), [periodStart, periodEnd]);
  const { data: identity } = useIpcQuery(() => window.api.access.getIdentity(), []);
  const copy = COPY[report];
  return <div className="w-full space-y-3">
    <div>
      <div className="flex flex-wrap items-baseline gap-x-3 gap-y-1">
        <h2 className="text-lg font-semibold text-gray-900">{copy.title}</h2>
        <p className="text-sm text-gray-500">{copy.note}</p>
      </div>
    </div>
    <div className="flex flex-wrap items-end gap-3 rounded border border-gray-200 bg-gray-50 p-3">
      <label className="text-sm"><span className="block text-gray-600">From</span><DateInput value={periodStart} onChange={setPeriodStart} className="mt-1 w-36" /></label>
      <label className="text-sm"><span className="block text-gray-600">To / as of</span><DateInput value={periodEnd} onChange={setPeriodEnd} className="mt-1 w-36" /></label>
      <span className="text-xs text-gray-500">Exports use exactly these dates and the table shown below.</span>
      {report === 'auditTrail' && <span className="text-xs text-gray-500"><span className="rounded bg-emerald-100 px-1.5 py-0.5 text-emerald-800">Current user</span> · other colors identify other users</span>}
    </div>
    {loading && <p className="text-sm text-gray-500">Loading report…</p>}
    {error && <div className="rounded bg-red-50 px-3 py-2 text-sm text-red-700">{error}</div>}
    {data && <ReportBody report={report} data={data} currentActor={identity?.name ?? null} openJournal={(id) => setView({ kind: 'journalForm', id })} />}
  </div>;
}

function ReportBody({ report, data, currentActor, openJournal }: { report: ComplianceReportPageKind; data: CompliancePackageResult; currentActor: string | null; openJournal: (id: number) => void }) {
  if (report === 'auditTrail') return data.auditTrail.length === 0 ? <Empty /> : <div className="overflow-x-auto"><table className="w-full min-w-[1050px] border-collapse text-sm"><thead><tr className="border-b"><Th>Changed</Th><Th>Entry date</Th><Th>User</Th><Th>Journal</Th><Th>Action</Th><Th>Field / line</Th><Th>Before</Th><Th>After</Th></tr></thead><tbody>{data.auditTrail.map((row) => <tr key={`${row.revisionId}:${row.journalEntryId}`} className={`border-b border-gray-100 ${userAuditStyle(row.createdBy, currentActor).row}`}><td className="px-3 py-1.5">{row.changedAt}</td><td className="px-3 py-1.5">{row.entryDate}</td><td className="px-3 py-1.5"><span className={`rounded px-2 py-0.5 text-xs ring-1 ${userAuditStyle(row.createdBy, currentActor).badge}`}>{row.createdBy ?? 'Legacy/local'}</span></td><td className="px-3 py-1.5">{row.journalEntryId === null ? '—' : <button className="text-brand-700 hover:underline" onClick={() => openJournal(row.journalEntryId!)}>Journal entry</button>}</td><td className="px-3 py-1.5">{row.action}</td><td className="px-3 py-1.5">{row.lineLabel ?? row.field}</td><td className="max-w-64 truncate px-3 py-1.5 text-gray-500" title={row.oldValue ?? ''}>{row.oldValue ?? '—'}</td><td className="max-w-64 truncate px-3 py-1.5" title={row.newValue ?? ''}>{row.newValue ?? '—'}</td></tr>)}</tbody></table></div>;

  if (report === 'sourceDocuments') {
    const missing = data.sourceDocuments.filter((row) => row.evidence === 'Missing').length;
    return <><div className="grid gap-3 sm:grid-cols-3"><Summary label="Documents / entries" value={data.sourceDocuments.length} /><Summary label="Evidence missing" value={missing} bad={missing > 0} /><Summary label="Supported" value={data.sourceDocuments.length - missing} /></div>{data.sourceDocuments.length === 0 ? <Empty /> : <div className="overflow-x-auto"><table className="w-full min-w-[950px] text-sm"><thead><tr className="border-b"><Th>Date</Th><Th>Type</Th><Th>Document</Th><Th>Party</Th><Th right>Amount</Th><Th>Evidence</Th><Th>GL</Th></tr></thead><tbody>{data.sourceDocuments.map((row, index) => <tr key={`${row.kind}:${row.documentNumber}:${index}`} className={row.evidence === 'Missing' ? 'border-b bg-rose-50/50' : 'border-b border-gray-100'}><td className="px-3 py-1.5">{row.date}</td><td className="px-3 py-1.5">{row.kind}</td><td className="px-3 py-1.5">{row.documentNumber}</td><td className="px-3 py-1.5">{row.party}</td><td className="px-3 py-1.5 text-right"><Money cents={row.amountCents} /></td><td className="px-3 py-1.5"><Badge bad={row.evidence === 'Missing'}>{row.evidence}</Badge>{row.evidenceName && <span className="ml-2 text-xs text-gray-500">{row.evidenceName}</span>}</td><td className="px-3 py-1.5">{row.journalEntryId ? <button className="text-brand-700 hover:underline" onClick={() => openJournal(row.journalEntryId!)}>Open GL</button> : '—'}</td></tr>)}</tbody></table></div>}</>;
  }

  if (report === 'bankDepositAnalysis') {
    const review = data.bankDeposits.filter((row) => row.requiresReview).length;
    return <><div className="grid gap-3 sm:grid-cols-3"><Summary label="Deposits" value={data.bankDeposits.length} /><Summary label="Total deposited" money={data.bankDeposits.reduce((sum, row) => sum + row.amountCents, 0)} /><Summary label="Needs explanation" value={review} bad={review > 0} /></div>{data.bankDeposits.length === 0 ? <Empty /> : <div className="overflow-x-auto"><table className="w-full min-w-[950px] text-sm"><thead><tr className="border-b"><Th>Date</Th><Th>Bank account</Th><Th right>Deposit</Th><Th>Classification</Th><Th>Memo / reference</Th><Th>Review</Th><Th>GL</Th></tr></thead><tbody>{data.bankDeposits.map((row, index) => <tr key={`${row.journalEntryId}:${index}`} className={row.requiresReview ? 'border-b bg-amber-50/60' : 'border-b border-gray-100'}><td className="px-3 py-1.5">{row.date}</td><td className="px-3 py-1.5">{row.bankAccount}</td><td className="px-3 py-1.5 text-right"><Money cents={row.amountCents} /></td><td className="px-3 py-1.5">{row.classification}</td><td className="px-3 py-1.5">{row.memo ?? row.reference ?? '—'}</td><td className="px-3 py-1.5"><Badge bad={row.requiresReview}>{row.requiresReview ? row.reviewReason : 'Explained by posting'}</Badge></td><td className="px-3 py-1.5"><button className="text-brand-700 hover:underline" onClick={() => openJournal(row.journalEntryId)}>Open GL</button></td></tr>)}</tbody></table></div>}</>;
  }

  if (report === 'payrollRegister') return <PayrollTable rows={data.payrollRegister} openJournal={openJournal} />;
  if (report === 'hstWorkingPaper') return <HstWorkingPaper data={data} openJournal={openJournal} />;
  if (report === 'fixedAssetContinuity') return <FixedAssetTable data={data} />;
  if (report === 'shareholderContinuity') return <ShareholderTable data={data} />;
  if (report === 'inventoryContinuity') return <InventoryTable data={data} />;
  if (report === 'debtContinuity') return <DebtTable data={data} />;
  return <T2Table data={data} />;
}

function Summary({ label, value, money, bad = false }: { label: string; value?: number; money?: number; bad?: boolean }) { return <div className={`rounded border p-3 ${bad ? 'border-rose-200 bg-rose-50' : 'border-gray-200 bg-white'}`}><p className="text-xs uppercase tracking-wide text-gray-500">{label}</p><p className={`mt-1 text-lg font-semibold ${bad ? 'text-rose-700' : 'text-gray-900'}`}>{money === undefined ? value : <Money cents={money} />}</p></div> }

function PayrollTable({ rows, openJournal }: { rows: CompliancePackageResult['payrollRegister']; openJournal: (id: number) => void }) {
  if (rows.length === 0) return <Empty />;
  return <div className="overflow-x-auto"><table className="w-full min-w-[1300px] text-sm"><thead><tr className="border-b"><Th>Pay date</Th><Th>Employee</Th><Th>Period</Th><Th right>Hours</Th><Th right>Gross</Th><Th right>CPP employee</Th><Th right>CPP employer</Th><Th right>EI employee</Th><Th right>EI employer</Th><Th right>Tax</Th><Th right>Net</Th><Th>Status / GL</Th></tr></thead><tbody>{rows.map((row) => <tr key={row.payrollRunId} className="border-b border-gray-100"><td className="px-3 py-1.5">{row.payDate}</td><td className="px-3 py-1.5 font-medium">{row.employee}</td><td className="px-3 py-1.5">{row.periodStart} – {row.periodEnd}</td><td className="px-3 py-1.5 text-right">{(row.regularHours ?? 0) + (row.overtimeHours ?? 0)}</td>{[row.grossPayCents, row.cppEmployeeCents, row.cppEmployerCents, row.eiEmployeeCents, row.eiEmployerCents, row.incomeTaxCents, row.netPayCents].map((amount, index) => <td key={index} className="px-3 py-1.5 text-right"><Money cents={amount} /></td>)}<td className="px-3 py-1.5"><Badge bad={row.status !== 'posted'}>{row.status}</Badge>{row.journalEntryId && <button className="ml-2 text-brand-700 hover:underline" onClick={() => openJournal(row.journalEntryId!)}>GL</button>}</td></tr>)}</tbody><tfoot><tr className="border-t-2 font-semibold"><td className="px-3 py-2" colSpan={4}>Total</td>{[rows.reduce((s,r)=>s+r.grossPayCents,0),rows.reduce((s,r)=>s+r.cppEmployeeCents,0),rows.reduce((s,r)=>s+r.cppEmployerCents,0),rows.reduce((s,r)=>s+r.eiEmployeeCents,0),rows.reduce((s,r)=>s+r.eiEmployerCents,0),rows.reduce((s,r)=>s+r.incomeTaxCents,0),rows.reduce((s,r)=>s+r.netPayCents,0)].map((amount,index)=><td key={index} className="px-3 py-2 text-right"><Money cents={amount}/></td>)}<td /></tr></tfoot></table></div>;
}

function HstWorkingPaper({ data, openJournal }: { data: CompliancePackageResult; openJournal: (id: number) => void }) { const hst=data.hstWorkingPaper; return <div className="space-y-3"><div className="grid gap-3 sm:grid-cols-3"><Summary label="Return lines" value={hst.boxes.length}/><Summary label="Manual items pending" value={hst.manualItemsPending} bad={hst.manualItemsPending>0}/><Summary label={hst.filedReturn?'Recorded as filed':'Not recorded as filed'} money={hst.filedReturn?.netPayableCents ?? 0}/></div><table className="w-full text-sm"><thead><tr className="border-b"><Th>CRA line</Th><Th>Description</Th><Th right>Amount</Th></tr></thead><tbody>{hst.boxes.map((row)=><tr key={row.box} className={row.box==='109'?'border-t-2 font-semibold':'border-b border-gray-100'}><td className="px-3 py-1.5 font-medium">{row.box}</td><td className="px-3 py-1.5">{row.label}</td><td className="px-3 py-1.5 text-right"><Money cents={row.amountCents}/></td></tr>)}</tbody></table>{hst.filedReturn&&<p className="rounded bg-emerald-50 px-3 py-2 text-sm text-emerald-800">Filed {hst.filedReturn.filingDate}. {hst.filedReturn.journalEntryId&&<button className="underline" onClick={()=>openJournal(hst.filedReturn!.journalEntryId!)}>Open filing GL</button>}</p>}<h3 className="font-semibold">Category support</h3><table className="w-full text-sm"><thead><tr className="border-b"><Th>Account</Th><Th>Direction</Th><Th right>Taxable base</Th><Th right>GST/HST</Th></tr></thead><tbody>{hst.categories.map((row,index)=><tr key={`${row.account}:${row.direction}:${index}`} className="border-b border-gray-100"><td className="px-3 py-1.5">{row.account}</td><td className="px-3 py-1.5">{row.direction==='collected'?'Collected':'ITC paid'}</td><td className="px-3 py-1.5 text-right"><Money cents={row.baseAmountCents}/></td><td className="px-3 py-1.5 text-right"><Money cents={row.hstCents}/></td></tr>)}</tbody></table><p className="text-xs text-amber-700">Lines 104 and 107 remain zero unless adjustments are posted separately. Confirm all figures against CRA My Business Account and supporting invoices before filing.</p></div> }

function FixedAssetRegisterTable({data}:{data:CompliancePackageResult}) {
  const rows = data.fixedAssetRegister ?? [];
  if (rows.length === 0) return null;
  const sum = (k: keyof (typeof rows)[number]) => rows.reduce((t, r) => t + (r[k] as number), 0);
  return (
    <div className="mb-3">
      <div className="mb-1 text-xs font-semibold uppercase tracking-wide text-gray-500">Book continuity — fixed asset register</div>
      <div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-sm"><thead><tr className="border-b"><Th>Asset</Th><Th>Class</Th><Th right>Opening cost</Th><Th right>Additions</Th><Th right>Disposals</Th><Th right>Opening acc. depr.</Th><Th right>Depreciation</Th><Th right>Closing cost</Th><Th right>Closing acc. depr.</Th><Th right>Net book value</Th><Th right>Proceeds</Th></tr></thead><tbody>
        {rows.map((r) => <tr key={r.name} className="border-b border-gray-100"><td className="px-3 py-1.5 font-medium">{r.name}</td><td className="px-3 py-1.5">{r.ccaClass ?? '—'}</td>{[r.openingCostCents, r.additionsCents, r.disposalsCents, r.openingAccumulatedCents, r.depreciationCents, r.closingCostCents, r.closingAccumulatedCents, r.closingBookValueCents, r.proceedsCents].map((amount, i) => <td key={i} className="px-3 py-1.5 text-right"><Money cents={amount} /></td>)}</tr>)}
        <tr className="border-t-2 border-gray-800 font-semibold"><td className="px-3 py-1.5">Total</td><td /> {(['openingCostCents','additionsCents','disposalsCents','openingAccumulatedCents','depreciationCents','closingCostCents','closingAccumulatedCents','closingBookValueCents','proceedsCents'] as const).map((k) => <td key={k} className="px-3 py-1.5 text-right"><Money cents={sum(k)} /></td>)}</tr>
      </tbody></table></div>
      <div className="mt-1 text-xs text-gray-400">Tax continuity (CCA pools) below. Additions here should match the year's pool additions; depreciation is the book charge, the CCA claim is the tax deduction.</div>
    </div>
  );
}
function FixedAssetTable({data}:{data:CompliancePackageResult}) { return <><FixedAssetRegisterTable data={data} />{data.fixedAssets.length===0?<Empty>No CCA pools end inside this period.</Empty>:<div className="overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead><tr className="border-b"><Th>Class</Th><Th>Year end</Th><Th right>Opening UCC</Th><Th right>Additions</Th><Th right>Dispositions</Th><Th right>CCA claim</Th><Th right>Closing UCC</Th><Th>Note</Th></tr></thead><tbody>{data.fixedAssets.map((row,index)=><tr key={`${row.classCode}:${index}`} className="border-b border-gray-100"><td className="px-3 py-1.5 font-medium">{row.classCode}</td><td className="px-3 py-1.5">{row.fiscalYearEnd}</td>{[row.openingUccCents,row.additionsCents,row.dispositionsCents,row.ccaClaimCents,row.closingUccCents].map((amount,i)=><td key={i} className="px-3 py-1.5 text-right"><Money cents={amount}/></td>)}<td className="px-3 py-1.5">{row.note??'—'}</td></tr>)}</tbody></table></div>}</> }
function ShareholderTable({data}:{data:CompliancePackageResult}) { return data.shareholders.length===0?<Empty>No shareholders configured.</Empty>:<div className="overflow-x-auto"><table className="w-full min-w-[950px] text-sm"><thead><tr className="border-b"><Th>Shareholder</Th><Th>Loan account</Th><Th right>Loan balance</Th><Th right>Eligible dividends</Th><Th right>Other dividends</Th><Th right>Interest</Th><Th>Identity</Th></tr></thead><tbody>{data.shareholders.map((row)=><tr key={row.shareholder} className="border-b border-gray-100"><td className="px-3 py-1.5 font-medium">{row.shareholder}</td><td className="px-3 py-1.5">{row.loanAccount??'Not linked'}</td><td className="px-3 py-1.5 text-right">{row.loanBalanceCents===null?'—':<Money cents={row.loanBalanceCents}/>}</td>{[row.eligibleDividendsCents,row.nonEligibleDividendsCents,row.interestCents].map((amount,i)=><td key={i} className="px-3 py-1.5 text-right"><Money cents={amount}/></td>)}<td className="px-3 py-1.5"><Badge bad={!row.identityComplete}>{row.identityComplete?'Complete':'SIN/BN missing'}</Badge></td></tr>)}</tbody></table></div> }
function InventoryTable({data}:{data:CompliancePackageResult}) { return data.inventory.length===0?<Empty>No tracked inventory products.</Empty>:<div className="overflow-x-auto"><table className="w-full min-w-[950px] text-sm"><thead><tr className="border-b"><Th>Product</Th><Th>SKU</Th><Th right>Opening qty</Th><Th right>Received</Th><Th right>Issued</Th><Th right>Closing qty</Th><Th right>Closing value</Th><Th>Exceptions</Th></tr></thead><tbody>{data.inventory.map((row)=><tr key={row.product} className={row.wentNegative||row.unlinkedMovementCount?'border-b bg-amber-50/50':'border-b border-gray-100'}><td className="px-3 py-1.5 font-medium">{row.product}</td><td className="px-3 py-1.5">{row.sku??'—'}</td>{[row.openingQuantity,row.quantityIn,row.quantityOut,row.closingQuantity].map((qty,i)=><td key={i} className="px-3 py-1.5 text-right tabular-nums">{qty}</td>)}<td className="px-3 py-1.5 text-right"><Money cents={row.closingValueCents}/></td><td className="px-3 py-1.5">{row.wentNegative?'Negative stock history':row.unlinkedMovementCount?`${row.unlinkedMovementCount} unlinked movement(s)`:'—'}</td></tr>)}</tbody></table></div> }
function DebtTable({data}:{data:CompliancePackageResult}) { return data.debt.length===0?<Empty>No loans configured.</Empty>:<div className="overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead><tr className="border-b"><Th>Loan</Th><Th>Lender</Th><Th>Start</Th><Th right>Rate</Th><Th right>Original principal</Th><Th>Linked liability</Th><Th right>Ledger balance</Th><Th>Status</Th></tr></thead><tbody>{data.debt.map((row)=><tr key={row.loan} className="border-b border-gray-100"><td className="px-3 py-1.5 font-medium">{row.loan}</td><td className="px-3 py-1.5">{row.lender??'—'}</td><td className="px-3 py-1.5">{row.startDate??'—'}</td><td className="px-3 py-1.5 text-right">{row.annualRate.toFixed(3)}%</td><td className="px-3 py-1.5 text-right"><Money cents={row.originalPrincipalCents}/></td><td className="px-3 py-1.5">{row.linkedAccount??'Not linked'}</td><td className="px-3 py-1.5 text-right">{row.ledgerBalanceCents===null?'—':<Money cents={row.ledgerBalanceCents}/>}</td><td className="px-3 py-1.5"><Badge bad={!row.isActive}>{row.isActive?'Active':'Inactive'}</Badge></td></tr>)}</tbody></table></div> }
function T2Table({data}:{data:CompliancePackageResult}) { const report=data.t2Reconciliation; return <div className="space-y-3"><div className="grid gap-3 sm:grid-cols-2"><Summary label="Preliminary income for tax review" money={report.preliminaryTaxableIncomeCents}/><Summary label="Accounts missing GIFI" value={report.unmappedGifiAccountCount} bad={report.unmappedGifiAccountCount>0}/></div><table className="w-full text-sm"><thead><tr className="border-b"><Th>Treatment</Th><Th>Working-paper line</Th><Th right>Amount</Th></tr></thead><tbody>{report.lines.map((line)=><tr key={line.label} className={line.treatment==='result'?'border-t-2 font-semibold':'border-b border-gray-100'}><td className="px-3 py-1.5 capitalize">{line.treatment}</td><td className="px-3 py-1.5">{line.label}</td><td className="px-3 py-1.5 text-right"><Money cents={line.amountCents}/></td></tr>)}</tbody></table><p className="rounded bg-amber-50 px-3 py-2 text-sm text-amber-800">{report.warning}</p></div> }
