import { useState } from 'react';
import type { ReactNode } from 'react';
import type { Section } from '@shared/domain/ledger/sectionHelpers';
import { DateInput } from '../../components/DateInput';
import { Money } from '../../components/Money';
import { useIpcQuery } from '../../hooks/useIpcQuery';
import { CustomTransactionDetailSheet } from './CustomTransactionDetailPage';
import { localIsoDate } from '@shared/domain/dates/localDate';

/** Re-exported so the column list has one definition. The sheet itself now lives in
 * CustomTransactionDetailPage, which is also a screen of its own. */
export { CUSTOM_REPORT_COLUMNS } from './CustomTransactionDetailPage';

function todayIso() { return localIsoDate() }
function yearStartIso() { return `${todayIso().slice(0, 4)}-01-01` }

const money = (value: number | null) => value === null ? '—' : <Money cents={value} />;

function ReportSection({ title, children }: { title: string; children: ReactNode }) {
  return <section className="space-y-2"><table className="w-full"><caption className="caption-top border-b border-brand-200 pb-1 text-left text-base font-semibold text-brand-900" data-export-row>{title}</caption></table>{children}</section>;
}

function FinancialSectionTable({ sections }: { sections: Section[] }) {
  return <table className="w-full text-sm"><thead><tr className="border-b"><th className="px-3 py-1.5 text-left">Account</th><th className="px-3 py-1.5 text-right">Amount</th></tr></thead><tbody>{sections.flatMap((section) => [<tr key={`${section.label}:head`} className="bg-gray-50 font-semibold"><td className="px-3 py-1.5" colSpan={2}>{section.label}</td></tr>, ...section.lines.map((line) => <tr key={`${section.label}:${line.account.id}`} className="border-b border-gray-100"><td className="px-3 py-1.5">{line.account.name}</td><td className="px-3 py-1.5 text-right"><Money cents={line.amountCents} /></td></tr>), <tr key={`${section.label}:total`} className="border-t font-semibold"><td className="px-3 py-1.5">Total {section.label}</td><td className="px-3 py-1.5 text-right"><Money cents={section.totalCents} /></td></tr>])}</tbody></table>;
}

export function ComprehensiveCompanyReportPage() {
  const [periodStart, setPeriodStart] = useState(yearStartIso());
  const [periodEnd, setPeriodEnd] = useState(todayIso());
  const { data, loading, error } = useIpcQuery(() => window.api.reports.comprehensiveCompany({ periodStart, periodEnd }), [periodStart, periodEnd]);
  const { data: company } = useIpcQuery(() => window.api.company.get(), []);

  return <div className="w-full space-y-3">
    <div>
      <h2 className="text-lg font-semibold text-gray-900">Comprehensive Company Report</h2>
      <p className="text-sm text-gray-500">Major financial statements, compliance schedules and a customizable transaction detail—exported together into one Excel worksheet.</p>
    </div>
    <div className="flex flex-wrap items-end gap-3 rounded border border-gray-200 bg-gray-50 p-3">
      <label className="text-sm"><span className="block text-gray-600">From</span><DateInput value={periodStart} onChange={setPeriodStart} className="mt-1 w-36" /></label>
      <label className="text-sm"><span className="block text-gray-600">To / as of</span><DateInput value={periodEnd} onChange={setPeriodEnd} className="mt-1 w-36" /></label>
      <span className="text-xs text-gray-500">Company: {company?.displayName || company?.legalName || 'Company'}</span>
    </div>
    {loading && <p className="text-sm text-gray-500">Preparing the complete company report…</p>}
    {error && <div className="rounded bg-red-50 px-3 py-2 text-sm text-red-700">{error}</div>}
    {data && <>
      <ReportSection title="Executive Summary"><table className="w-full text-sm"><tbody>{[
        ['Revenue', data.incomeStatement.revenue.totalCents], ['Cost of sales', data.incomeStatement.costOfSales.totalCents], ['Gross profit', data.incomeStatement.grossProfitCents], ['Operating expenses', data.incomeStatement.operatingExpenses.totalCents], ['Net income', data.incomeStatement.netIncomeCents], ['Total assets', data.balanceSheet.assets.totalCents], ['Total liabilities', data.balanceSheet.liabilities.totalCents], ['Total equity', data.balanceSheet.equity.totalCents], ['Closing cash', data.cashFlow.closingCashCents],
      ].map(([label, amount]) => <tr key={String(label)} className="border-b border-gray-100"><td className="px-3 py-1.5">{label}</td><td className="px-3 py-1.5 text-right"><Money cents={Number(amount)} /></td></tr>)}</tbody></table></ReportSection>

      <ReportSection title="Profit and Loss"><FinancialSectionTable sections={[data.incomeStatement.revenue, data.incomeStatement.costOfSales, data.incomeStatement.operatingExpenses]} /></ReportSection>
      <ReportSection title="Balance Sheet"><FinancialSectionTable sections={[data.balanceSheet.assets, data.balanceSheet.liabilities, data.balanceSheet.equity]} /></ReportSection>
      <ReportSection title="Statement of Cash Flows"><table className="w-full text-sm"><tbody>{[data.cashFlow.operating, data.cashFlow.investing, data.cashFlow.financing].flatMap((section) => [<tr key={`${section.label}:head`} className="bg-gray-50 font-semibold"><td className="px-3 py-1.5" colSpan={2}>{section.label}</td></tr>, ...section.lines.map((line, index) => <tr key={`${section.label}:${index}`} className="border-b border-gray-100"><td className="px-3 py-1.5">{line.label}</td><td className="px-3 py-1.5 text-right"><Money cents={line.amountCents} /></td></tr>), <tr key={`${section.label}:total`} className="font-semibold"><td className="px-3 py-1.5">Total {section.label}</td><td className="px-3 py-1.5 text-right"><Money cents={section.totalCents} /></td></tr>])}<tr className="border-t-2 font-semibold"><td className="px-3 py-1.5">Closing cash</td><td className="px-3 py-1.5 text-right"><Money cents={data.cashFlow.closingCashCents} /></td></tr></tbody></table></ReportSection>
      <ReportSection title="Trial Balance"><table className="w-full text-sm"><thead><tr className="border-b"><th className="px-3 py-1.5 text-left">Account</th><th className="px-3 py-1.5 text-right">Debit</th><th className="px-3 py-1.5 text-right">Credit</th></tr></thead><tbody>{data.trialBalance.rows.map((row) => <tr key={row.account.id} className="border-b border-gray-100"><td className="px-3 py-1.5">{row.account.name}</td><td className="px-3 py-1.5 text-right">{row.debitCents ? <Money cents={row.debitCents} /> : '—'}</td><td className="px-3 py-1.5 text-right">{row.creditCents ? <Money cents={row.creditCents} /> : '—'}</td></tr>)}</tbody><tfoot><tr className="border-t-2 font-semibold"><td className="px-3 py-1.5">Total</td><td className="px-3 py-1.5 text-right"><Money cents={data.trialBalance.totalDebitCents} /></td><td className="px-3 py-1.5 text-right"><Money cents={data.trialBalance.totalCreditCents} /></td></tr></tfoot></table></ReportSection>

      <ReportSection title="GST/HST Working Paper"><table className="w-full text-sm"><thead><tr className="border-b"><th className="px-3 py-1.5 text-left">CRA line</th><th className="px-3 py-1.5 text-left">Description</th><th className="px-3 py-1.5 text-right">Amount</th></tr></thead><tbody>{data.compliance.hstWorkingPaper.boxes.map((row) => <tr key={row.box} className="border-b border-gray-100"><td className="px-3 py-1.5">{row.box}</td><td className="px-3 py-1.5">{row.label}</td><td className="px-3 py-1.5 text-right"><Money cents={row.amountCents} /></td></tr>)}</tbody></table></ReportSection>
      <ReportSection title="Payroll Register"><table className="w-full text-sm"><thead><tr className="border-b"><th className="px-3 py-1.5 text-left">Pay date</th><th className="px-3 py-1.5 text-left">Employee</th><th className="px-3 py-1.5 text-right">Gross</th><th className="px-3 py-1.5 text-right">Deductions</th><th className="px-3 py-1.5 text-right">Net</th></tr></thead><tbody>{data.compliance.payrollRegister.map((row) => <tr key={row.payrollRunId} className="border-b border-gray-100"><td className="px-3 py-1.5">{row.payDate}</td><td className="px-3 py-1.5">{row.employee}</td><td className="px-3 py-1.5 text-right"><Money cents={row.grossPayCents} /></td><td className="px-3 py-1.5 text-right"><Money cents={row.cppEmployeeCents + row.eiEmployeeCents + row.incomeTaxCents} /></td><td className="px-3 py-1.5 text-right"><Money cents={row.netPayCents} /></td></tr>)}</tbody></table></ReportSection>
      <ReportSection title="Source Documents and Evidence"><table className="w-full text-sm"><thead><tr className="border-b"><th className="px-3 py-1.5 text-left">Date</th><th className="px-3 py-1.5 text-left">Type</th><th className="px-3 py-1.5 text-left">Document</th><th className="px-3 py-1.5 text-left">Party</th><th className="px-3 py-1.5 text-right">Amount</th><th className="px-3 py-1.5 text-left">Evidence</th></tr></thead><tbody>{data.compliance.sourceDocuments.map((row, index) => <tr key={`${row.kind}:${index}`} className="border-b border-gray-100"><td className="px-3 py-1.5">{row.date}</td><td className="px-3 py-1.5">{row.kind}</td><td className="px-3 py-1.5">{row.documentNumber}</td><td className="px-3 py-1.5">{row.party}</td><td className="px-3 py-1.5 text-right"><Money cents={row.amountCents} /></td><td className="px-3 py-1.5">{row.evidence}</td></tr>)}</tbody></table></ReportSection>
      <ReportSection title="Accounts Receivable Ageing (A/R)"><table className="w-full text-sm"><thead><tr className="border-b"><th className="px-3 py-1.5 text-left">Customer</th><th className="px-3 py-1.5 text-left">Invoice</th><th className="px-3 py-1.5 text-left">Due</th><th className="px-3 py-1.5 text-left">Age bucket</th><th className="px-3 py-1.5 text-right">Balance</th></tr></thead><tbody>{data.receivables.map((row) => <tr key={`${row.documentNumber}:${row.party}`} className="border-b border-gray-100"><td className="px-3 py-1.5">{row.party}</td><td className="px-3 py-1.5">{row.documentNumber}</td><td className="px-3 py-1.5">{row.dueDate}</td><td className="px-3 py-1.5">{row.bucket}</td><td className="px-3 py-1.5 text-right"><Money cents={row.balanceCents} /></td></tr>)}</tbody></table></ReportSection>
      <ReportSection title="Accounts Payable Ageing (A/P)"><table className="w-full text-sm"><thead><tr className="border-b"><th className="px-3 py-1.5 text-left">Vendor</th><th className="px-3 py-1.5 text-left">Bill</th><th className="px-3 py-1.5 text-left">Due</th><th className="px-3 py-1.5 text-left">Age bucket</th><th className="px-3 py-1.5 text-right">Balance</th></tr></thead><tbody>{data.payables.map((row) => <tr key={`${row.documentNumber}:${row.party}`} className="border-b border-gray-100"><td className="px-3 py-1.5">{row.party}</td><td className="px-3 py-1.5">{row.documentNumber}</td><td className="px-3 py-1.5">{row.dueDate}</td><td className="px-3 py-1.5">{row.bucket}</td><td className="px-3 py-1.5 text-right"><Money cents={row.balanceCents} /></td></tr>)}</tbody></table></ReportSection>
      <ReportSection title="Sales by Customer"><table className="w-full text-sm"><thead><tr className="border-b"><th className="px-3 py-1.5 text-left">Customer</th><th className="px-3 py-1.5 text-right">Documents</th><th className="px-3 py-1.5 text-right">Invoiced</th><th className="px-3 py-1.5 text-right">Receipted</th><th className="px-3 py-1.5 text-right">Total</th></tr></thead><tbody>{data.salesByCustomer.map((row) => <tr key={row.customer} className="border-b border-gray-100"><td className="px-3 py-1.5">{row.customer}</td><td className="px-3 py-1.5 text-right">{row.documentCount}</td><td className="px-3 py-1.5 text-right"><Money cents={row.invoicedCents} /></td><td className="px-3 py-1.5 text-right"><Money cents={row.receiptedCents} /></td><td className="px-3 py-1.5 text-right"><Money cents={row.invoicedCents + row.receiptedCents} /></td></tr>)}</tbody></table></ReportSection>
      <ReportSection title="Expenses by Vendor"><table className="w-full text-sm"><thead><tr className="border-b"><th className="px-3 py-1.5 text-left">Vendor</th><th className="px-3 py-1.5 text-right">Transactions</th><th className="px-3 py-1.5 text-left">Top accounts</th><th className="px-3 py-1.5 text-right">Amount</th></tr></thead><tbody>{data.expensesByVendor.rows.map((row) => <tr key={row.vendorName} className="border-b border-gray-100"><td className="px-3 py-1.5">{row.vendorName}</td><td className="px-3 py-1.5 text-right">{row.transactionCount}</td><td className="px-3 py-1.5">{row.topAccounts.map((account) => account.accountName).join(', ') || '—'}</td><td className="px-3 py-1.5 text-right"><Money cents={row.amountCents} /></td></tr>)}</tbody></table></ReportSection>
      <ReportSection title="Continuity and Compliance Summary"><table className="w-full text-sm"><thead><tr className="border-b"><th className="px-3 py-1.5 text-left">Schedule</th><th className="px-3 py-1.5 text-right">Items</th><th className="px-3 py-1.5 text-left">Review note</th></tr></thead><tbody>{[
        ['Audit trail changes', data.compliance.auditTrail.length, 'Full change history retained'], ['Bank deposits', data.compliance.bankDeposits.length, `${data.compliance.bankDeposits.filter((row) => row.requiresReview).length} require review`], ['Fixed asset / CCA classes', data.compliance.fixedAssets.length, 'Opening-to-closing continuity'], ['Shareholders', data.compliance.shareholders.length, `${data.compliance.shareholders.filter((row) => !row.identityComplete).length} missing identity details`], ['Inventory products', data.compliance.inventory.length, `${data.compliance.inventory.filter((row) => row.wentNegative || row.unlinkedMovementCount).length} exceptions`], ['Loans and debt', data.compliance.debt.length, 'Linked to liability balances'], ['Accounts missing GIFI', data.compliance.t2Reconciliation.unmappedGifiAccountCount, 'T2 mapping review'],
      ].map(([label, count, note]) => <tr key={String(label)} className="border-b border-gray-100"><td className="px-3 py-1.5">{label}</td><td className="px-3 py-1.5 text-right">{count}</td><td className="px-3 py-1.5">{note}</td></tr>)}</tbody></table></ReportSection>

      <ReportSection title="Bank Deposit Analysis"><table className="w-full text-sm"><thead><tr className="border-b"><th className="px-3 py-1.5 text-left">Date</th><th className="px-3 py-1.5 text-left">Bank account</th><th className="px-3 py-1.5 text-left">Classification</th><th className="px-3 py-1.5 text-right">Amount</th><th className="px-3 py-1.5 text-left">Review</th></tr></thead><tbody>{data.compliance.bankDeposits.map((row, index) => <tr key={`${row.journalEntryId}:${index}`} className="border-b border-gray-100"><td className="px-3 py-1.5">{row.date}</td><td className="px-3 py-1.5">{row.bankAccount}</td><td className="px-3 py-1.5">{row.classification}</td><td className="px-3 py-1.5 text-right"><Money cents={row.amountCents} /></td><td className="px-3 py-1.5">{row.reviewReason ?? 'Reviewed by posting'}</td></tr>)}</tbody></table></ReportSection>
      <ReportSection title="Fixed Asset and CCA Continuity"><table className="w-full text-sm"><thead><tr className="border-b"><th className="px-3 py-1.5 text-left">Class</th><th className="px-3 py-1.5 text-right">Opening UCC</th><th className="px-3 py-1.5 text-right">Additions</th><th className="px-3 py-1.5 text-right">Dispositions</th><th className="px-3 py-1.5 text-right">CCA</th><th className="px-3 py-1.5 text-right">Closing UCC</th></tr></thead><tbody>{data.compliance.fixedAssets.map((row, index) => <tr key={`${row.classCode}:${index}`} className="border-b border-gray-100"><td className="px-3 py-1.5">{row.classCode}</td>{[row.openingUccCents, row.additionsCents, row.dispositionsCents, row.ccaClaimCents, row.closingUccCents].map((amount, amountIndex) => <td key={amountIndex} className="px-3 py-1.5 text-right"><Money cents={amount} /></td>)}</tr>)}</tbody></table></ReportSection>
      <ReportSection title="Shareholder and Related-Party Continuity"><table className="w-full text-sm"><thead><tr className="border-b"><th className="px-3 py-1.5 text-left">Shareholder</th><th className="px-3 py-1.5 text-left">Loan account</th><th className="px-3 py-1.5 text-right">Loan balance</th><th className="px-3 py-1.5 text-right">Dividends</th><th className="px-3 py-1.5 text-right">Interest</th><th className="px-3 py-1.5 text-left">Identity</th></tr></thead><tbody>{data.compliance.shareholders.map((row) => <tr key={row.shareholder} className="border-b border-gray-100"><td className="px-3 py-1.5">{row.shareholder}</td><td className="px-3 py-1.5">{row.loanAccount ?? 'Not linked'}</td><td className="px-3 py-1.5 text-right">{money(row.loanBalanceCents)}</td><td className="px-3 py-1.5 text-right"><Money cents={row.eligibleDividendsCents + row.nonEligibleDividendsCents} /></td><td className="px-3 py-1.5 text-right"><Money cents={row.interestCents} /></td><td className="px-3 py-1.5">{row.identityComplete ? 'Complete' : 'Missing details'}</td></tr>)}</tbody></table></ReportSection>
      <ReportSection title="Inventory Movement and Valuation"><table className="w-full text-sm"><thead><tr className="border-b"><th className="px-3 py-1.5 text-left">Product</th><th className="px-3 py-1.5 text-left">SKU</th><th className="px-3 py-1.5 text-right">Opening</th><th className="px-3 py-1.5 text-right">Received</th><th className="px-3 py-1.5 text-right">Issued</th><th className="px-3 py-1.5 text-right">Closing</th><th className="px-3 py-1.5 text-right">Value</th><th className="px-3 py-1.5 text-left">Exception</th></tr></thead><tbody>{data.compliance.inventory.map((row) => <tr key={row.product} className="border-b border-gray-100"><td className="px-3 py-1.5">{row.product}</td><td className="px-3 py-1.5">{row.sku ?? '—'}</td>{[row.openingQuantity, row.quantityIn, row.quantityOut, row.closingQuantity].map((quantity, index) => <td key={index} className="px-3 py-1.5 text-right">{quantity}</td>)}<td className="px-3 py-1.5 text-right"><Money cents={row.closingValueCents} /></td><td className="px-3 py-1.5">{row.wentNegative ? 'Negative stock' : row.unlinkedMovementCount ? `${row.unlinkedMovementCount} unlinked` : '—'}</td></tr>)}</tbody></table></ReportSection>
      <ReportSection title="Debt Continuity"><table className="w-full text-sm"><thead><tr className="border-b"><th className="px-3 py-1.5 text-left">Loan</th><th className="px-3 py-1.5 text-left">Lender</th><th className="px-3 py-1.5 text-right">Principal</th><th className="px-3 py-1.5 text-right">Rate</th><th className="px-3 py-1.5 text-left">Linked account</th><th className="px-3 py-1.5 text-right">Ledger balance</th></tr></thead><tbody>{data.compliance.debt.map((row) => <tr key={row.loan} className="border-b border-gray-100"><td className="px-3 py-1.5">{row.loan}</td><td className="px-3 py-1.5">{row.lender ?? '—'}</td><td className="px-3 py-1.5 text-right"><Money cents={row.originalPrincipalCents} /></td><td className="px-3 py-1.5 text-right">{row.annualRate}%</td><td className="px-3 py-1.5">{row.linkedAccount ?? 'Not linked'}</td><td className="px-3 py-1.5 text-right">{money(row.ledgerBalanceCents)}</td></tr>)}</tbody></table></ReportSection>
      <ReportSection title="T2 Preliminary Tax Reconciliation"><table className="w-full text-sm"><thead><tr className="border-b"><th className="px-3 py-1.5 text-left">Treatment</th><th className="px-3 py-1.5 text-left">Line</th><th className="px-3 py-1.5 text-right">Amount</th></tr></thead><tbody>{data.compliance.t2Reconciliation.lines.map((row) => <tr key={row.label} className="border-b border-gray-100"><td className="px-3 py-1.5">{row.treatment}</td><td className="px-3 py-1.5">{row.label}</td><td className="px-3 py-1.5 text-right"><Money cents={row.amountCents} /></td></tr>)}</tbody></table></ReportSection>
      <ReportSection title="Audit Trail and Change History"><table className="w-full text-sm"><thead><tr className="border-b"><th className="px-3 py-1.5 text-left">Changed</th><th className="px-3 py-1.5 text-left">User</th><th className="px-3 py-1.5 text-left">Action</th><th className="px-3 py-1.5 text-left">Field / document</th><th className="px-3 py-1.5 text-left">Before</th><th className="px-3 py-1.5 text-left">After</th></tr></thead><tbody>{data.compliance.auditTrail.map((row) => <tr key={`${row.revisionId}:${row.journalEntryId}`} className="border-b border-gray-100"><td className="px-3 py-1.5">{row.changedAt}</td><td className="px-3 py-1.5">{row.createdBy ?? 'Legacy/local'}</td><td className="px-3 py-1.5">{row.action}</td><td className="px-3 py-1.5">{row.lineLabel ?? row.field}</td><td className="px-3 py-1.5">{row.oldValue ?? '—'}</td><td className="px-3 py-1.5">{row.newValue ?? '—'}</td></tr>)}</tbody></table></ReportSection>

      <ReportSection title="Customizable Transaction Detail">
        <CustomTransactionDetailSheet rows={data.customRows} />
      </ReportSection>
    </>}
  </div>;
}
